### ISSUE TITLE
Honor PETSC_DIR and PETSC_ARCH

### ISSUE THREAD

**Issue by gtheler** [jam4375/plasmatic-cpp#1]
Hi Jason! Can you make cmake honor these two environment variables?
I wouldn't know how to do it myself. I am more of an autotools guy.

**Comment by jam4375** [comment]
Hi Jeremy! Currently it uses CMake's `FindPkgConfig` to read the configuration from a `petsc.pc` file provided by PETSC. As long as the PETSc version you are using is 3.12 or newer this should be there and working. This is based on a recommendation from Jed Brown here: https://github.com/jedbrown/cmake-modules/commit/89cfd5088fa9362c63e15c6b346da9565f23e6a4

If you run cmake with this command it should find PETSc I think:
```
cmake -DCMAKE_PREFIX_PATH=$PETSC_DIR ..
```
I'm not sure how to get it to respect the `PETSC_ARCH` environment variable but you might also try running the CMake command as:
```
cmake -DCMAKE_PREFIX_PATH=$PETSC_DIR/$PETSC_ARCH ..
```

Keep in mind this code is pretty slow right now :)

**Comment by gtheler** [comment]
Fair enough, `cmake -DCMAKE_PREFIX_PATH=$PETSC_DIR/$PETSC_ARCH ..` worked (no idea why) so I'll close the issue.
